# -*- coding: utf-8 -*-

# This script defines widgets and related windows of the "Versuchsaufbau" window.

import sys
sys.path.append('gui')
from PyQt5 import QtCore, QtGui, QtWidgets
import cv2 as cv


# This class defines the "Auswahl des Systemkontollers" window
# The functions are not completed and activated.
# It's Qt-Designer file is "SystemControllerSelection.ui" in folder "uifiles"
class Ui_SystemControllerSelection(object):
    def setupUi(self, SystemControllerSelection):
        SystemControllerSelection.setObjectName("SystemControllerSelection")
        SystemControllerSelection.resize(640, 480)
        SystemControllerSelection.setMinimumSize(QtCore.QSize(640, 480))
        SystemControllerSelection.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        SystemControllerSelection.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon_materials/4.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        SystemControllerSelection.setWindowIcon(icon)
        SystemControllerSelection.setModal(True)

        self.AuswahlList = QtWidgets.QListWidget(SystemControllerSelection)
        self.AuswahlList.setGeometry(QtCore.QRect(55, 90, 531, 301))
        self.AuswahlList.setMinimumSize(QtCore.QSize(531, 301))
        self.AuswahlList.setMaximumSize(QtCore.QSize(531, 301))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.AuswahlList.setFont(font)
        self.AuswahlList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.AuswahlList.setObjectName("AuswahlList")
        item = QtWidgets.QListWidgetItem()
        self.AuswahlList.addItem(item)

        self.HPSystemController = QtWidgets.QCheckBox() # Instantiate a checkBox
        self.HPSystemController.setObjectName("HPSystemController")
        item = QtWidgets.QListWidgetItem() # Instantiate an Item.QListWidget，but the checkBox can not be added into it directly
        self.AuswahlList.addItem(item)  # add the QListWidgetItem into QListWidget
        self.AuswahlList.setItemWidget(item, self.HPSystemController) # then add the checkBox into QListWidgetItem

        self.LabelKontroller = QtWidgets.QLabel(SystemControllerSelection)
        self.LabelKontroller.setGeometry(QtCore.QRect(180, 50, 281, 31))
        self.LabelKontroller.setMinimumSize(QtCore.QSize(281, 31))
        self.LabelKontroller.setMaximumSize(QtCore.QSize(281, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LabelKontroller.setFont(font)
        self.LabelKontroller.setObjectName("LabelKontroller")

        self.ApplyButton = QtWidgets.QPushButton(SystemControllerSelection)
        self.ApplyButton.setGeometry(QtCore.QRect(320, 410, 121, 41))
        self.ApplyButton.setMinimumSize(QtCore.QSize(121, 41))
        self.ApplyButton.setMaximumSize(QtCore.QSize(121, 41))
        self.ApplyButton.setAutoDefault(False)
        self.ApplyButton.setDefault(True)
        self.ApplyButton.setObjectName("ApplyButton")

        self.CancelButton = QtWidgets.QPushButton(SystemControllerSelection)
        self.CancelButton.setGeometry(QtCore.QRect(460, 410, 121, 41))
        self.CancelButton.setMinimumSize(QtCore.QSize(121, 41))
        self.CancelButton.setMaximumSize(QtCore.QSize(121, 41))
        self.CancelButton.setObjectName("CancelButton")

        self.retranslateUi(SystemControllerSelection)
        # define signals
        self.CancelButton.clicked['bool'].connect(SystemControllerSelection.close)
        QtCore.QMetaObject.connectSlotsByName(SystemControllerSelection)

        # define the background color of the window
        pale = QtGui.QPalette()
        pale.setColor(QtGui.QPalette.Background, QtGui.QColor(248, 248, 248))
        SystemControllerSelection.setPalette(pale)

    def retranslateUi(self, SystemControllerSelection):
        _translate = QtCore.QCoreApplication.translate
        SystemControllerSelection.setWindowTitle(_translate("SystemControllerSelection", "Auswahl des Systemkontrollers"))
        __sortingEnabled = self.AuswahlList.isSortingEnabled()
        self.AuswahlList.setSortingEnabled(False)
        item = self.AuswahlList.item(0)
        item.setText(_translate("SystemControllerSelection", "New Item"))
        self.AuswahlList.setSortingEnabled(__sortingEnabled)
        self.LabelKontroller.setText(_translate("SystemControllerSelection", "Verfügbare Systemkontroller"))
        self.ApplyButton.setText(_translate("SystemControllerSelection", "Anwenden"))
        self.CancelButton.setText(_translate("SystemControllerSelection", "Zurück"))
        self.HPSystemController.setText(_translate("SystemControllerSelection", "Hp SystemController."))

# This class defines the "Edit Signal Routing" window
# The functions are not completed and activated.
# It's Qt-Designer file is "EditSignalRouting.ui" in folder "uifiles"
class Ui_EditSignalRouting(object):
    def setupUi(self, EditSignalRouting):

        EditSignalRouting.setObjectName("EditSignalRouting")
        EditSignalRouting.resize(1280, 720)
        EditSignalRouting.setMinimumSize(QtCore.QSize(1280, 720))
        EditSignalRouting.setMaximumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        EditSignalRouting.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon_materials/4.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        EditSignalRouting.setWindowIcon(icon)

        self.ApplyButton = QtWidgets.QPushButton(EditSignalRouting)
        self.ApplyButton.setGeometry(QtCore.QRect(950, 650, 131, 41))
        self.ApplyButton.setMinimumSize(QtCore.QSize(131, 41))
        self.ApplyButton.setMaximumSize(QtCore.QSize(131, 41))
        self.ApplyButton.setDefault(True)
        self.ApplyButton.setObjectName("ApplyButton")

        self.CancelButton = QtWidgets.QPushButton(EditSignalRouting)
        self.CancelButton.setGeometry(QtCore.QRect(1100, 650, 131, 41))
        self.CancelButton.setMinimumSize(QtCore.QSize(131, 41))
        self.CancelButton.setMaximumSize(QtCore.QSize(131, 41))
        self.CancelButton.setObjectName("CancelButton")

        self.HelptoolButton = QtWidgets.QToolButton(EditSignalRouting)
        self.HelptoolButton.setGeometry(QtCore.QRect(50, 650, 131, 41))
        self.HelptoolButton.setMinimumSize(QtCore.QSize(131, 41))
        self.HelptoolButton.setMaximumSize(QtCore.QSize(131, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon_materials/9.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.HelptoolButton.setIcon(icon1)
        self.HelptoolButton.setIconSize(QtCore.QSize(41, 41))
        self.HelptoolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.HelptoolButton.setObjectName("HelptoolButton")

        self.Monitoring = QtWidgets.QTabWidget(EditSignalRouting)
        self.Monitoring.setGeometry(QtCore.QRect(50, 310, 1181, 311))
        self.Monitoring.setMinimumSize(QtCore.QSize(1181, 311))
        self.Monitoring.setMaximumSize(QtCore.QSize(1181, 311))
        self.Monitoring.setObjectName("Monitoring")

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.treeWidget = QtWidgets.QTreeWidget(self.tab)
        self.treeWidget.setGeometry(QtCore.QRect(20, 20, 361, 241))
        self.treeWidget.setMinimumSize(QtCore.QSize(361, 241))
        self.treeWidget.setMaximumSize(QtCore.QSize(361, 241))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.treeWidget.setFont(font)
        self.treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeWidget.setTabKeyNavigation(False)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setWordWrap(False)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setExpandsOnDoubleClick(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)

        self.BackgroundLabel1 = QtWidgets.QLabel(self.tab)
        self.BackgroundLabel1.setGeometry(QtCore.QRect(600, 20, 361, 241))
        self.BackgroundLabel1.setObjectName("BackgroundLabel1")

        self.Monitoring.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.AuxiliaryOutputsLabel = QtWidgets.QLabel(self.tab_2)
        self.AuxiliaryOutputsLabel.setGeometry(QtCore.QRect(20, 10, 121, 21))
        self.AuxiliaryOutputsLabel.setMinimumSize(QtCore.QSize(121, 21))
        self.AuxiliaryOutputsLabel.setMaximumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.AuxiliaryOutputsLabel.setFont(font)
        self.AuxiliaryOutputsLabel.setObjectName("AuxiliaryOutputsLabel")

        self.SwitchPositionLabel = QtWidgets.QLabel(self.tab_2)
        self.SwitchPositionLabel.setGeometry(QtCore.QRect(500, 10, 661, 21))
        self.SwitchPositionLabel.setMinimumSize(QtCore.QSize(661, 21))
        self.SwitchPositionLabel.setMaximumSize(QtCore.QSize(661, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SwitchPositionLabel.setFont(font)
        self.SwitchPositionLabel.setObjectName("SwitchPositionLabel")

        self.OutPutTree = QtWidgets.QTreeWidget(self.tab_2)
        self.OutPutTree.setGeometry(QtCore.QRect(20, 40, 461, 221))
        self.OutPutTree.setMinimumSize(QtCore.QSize(461, 221))
        self.OutPutTree.setMaximumSize(QtCore.QSize(461, 221))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.OutPutTree.setFont(font)
        self.OutPutTree.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.OutPutTree.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.OutPutTree.setObjectName("OutPutTree")
        self.OutPutTree.header().setVisible(False)

        self.PositionTable = QtWidgets.QTableWidget(self.tab_2)
        self.PositionTable.setGeometry(QtCore.QRect(500, 40, 661, 221))
        self.PositionTable.setMinimumSize(QtCore.QSize(661, 221))
        self.PositionTable.setMaximumSize(QtCore.QSize(661, 221))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.PositionTable.setFont(font)
        self.PositionTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.PositionTable.setObjectName("PositionTable")
        self.PositionTable.setColumnCount(2)
        self.PositionTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.PositionTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.PositionTable.setHorizontalHeaderItem(1, item)

        self.Monitoring.addTab(self.tab_2, "")

        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")

        self.UserMessageEdit = QtWidgets.QTextEdit(self.tab_3)
        self.UserMessageEdit.setGeometry(QtCore.QRect(20, 40, 1131, 81))
        self.UserMessageEdit.setMinimumSize(QtCore.QSize(1131, 81))
        self.UserMessageEdit.setMaximumSize(QtCore.QSize(1131, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.UserMessageEdit.setFont(font)
        self.UserMessageEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.UserMessageEdit.setObjectName("UserMessageEdit")

        self.UserMessageEditor2 = QtWidgets.QTextEdit(self.tab_3)
        self.UserMessageEditor2.setEnabled(False)
        self.UserMessageEditor2.setGeometry(QtCore.QRect(20, 180, 1131, 81))
        self.UserMessageEditor2.setMinimumSize(QtCore.QSize(1131, 81))
        self.UserMessageEditor2.setMaximumSize(QtCore.QSize(1131, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.UserMessageEditor2.setFont(font)
        self.UserMessageEditor2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.UserMessageEditor2.setObjectName("UserMessageEditor2")

        self.UserMessageLabel = QtWidgets.QLabel(self.tab_3)
        self.UserMessageLabel.setGeometry(QtCore.QRect(20, 10, 171, 21))
        self.UserMessageLabel.setMinimumSize(QtCore.QSize(171, 21))
        self.UserMessageLabel.setMaximumSize(QtCore.QSize(171, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.UserMessageLabel.setFont(font)
        self.UserMessageLabel.setObjectName("UserMessageLabel")

        self.UserMessageTest = QtWidgets.QLabel(self.tab_3)
        self.UserMessageTest.setEnabled(False)
        self.UserMessageTest.setGeometry(QtCore.QRect(20, 150, 211, 21))
        self.UserMessageTest.setMinimumSize(QtCore.QSize(211, 21))
        self.UserMessageTest.setMaximumSize(QtCore.QSize(211, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.UserMessageTest.setFont(font)
        self.UserMessageTest.setObjectName("UserMessageTest")

        self.UserMessageCheckBox = QtWidgets.QCheckBox(self.tab_3)
        self.UserMessageCheckBox.setEnabled(False)
        self.UserMessageCheckBox.setGeometry(QtCore.QRect(270, 150, 401, 21))
        self.UserMessageCheckBox.setMinimumSize(QtCore.QSize(401, 21))
        self.UserMessageCheckBox.setMaximumSize(QtCore.QSize(401, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.UserMessageCheckBox.setFont(font)
        self.UserMessageCheckBox.setChecked(True)
        self.UserMessageCheckBox.setObjectName("UserMessageCheckBox")

        self.Monitoring.addTab(self.tab_3, "")

        self.expectedSetup = QtWidgets.QGroupBox(EditSignalRouting)
        self.expectedSetup.setGeometry(QtCore.QRect(50, 100, 1181, 191))
        self.expectedSetup.setMinimumSize(QtCore.QSize(1181, 191))
        self.expectedSetup.setMaximumSize(QtCore.QSize(1181, 191))
        self.expectedSetup.setObjectName("expectedSetup")

        self.EUTButton = QtWidgets.QPushButton(self.expectedSetup)
        self.EUTButton.setGeometry(QtCore.QRect(250, 20, 100, 61))
        self.EUTButton.setMinimumSize(QtCore.QSize(100, 61))
        self.EUTButton.setMaximumSize(QtCore.QSize(100, 61))
        self.EUTButton.setObjectName("EUTButton")

        self.AntenneEmpangButton = QtWidgets.QPushButton(self.expectedSetup)
        self.AntenneEmpangButton.setGeometry(QtCore.QRect(390, 20, 120, 61))
        self.AntenneEmpangButton.setMinimumSize(QtCore.QSize(120, 61))
        self.AntenneEmpangButton.setMaximumSize(QtCore.QSize(120, 61))
        self.AntenneEmpangButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.AntenneEmpangButton.setAutoExclusive(False)
        self.AntenneEmpangButton.setObjectName("AntenneEmpangButton")

        self.KabelButton = QtWidgets.QPushButton(self.expectedSetup)
        self.KabelButton.setGeometry(QtCore.QRect(550, 20, 100, 61))
        self.KabelButton.setMinimumSize(QtCore.QSize(100, 61))
        self.KabelButton.setMaximumSize(QtCore.QSize(100, 61))
        self.KabelButton.setObjectName("KabelButton")

        self.AltenButton = QtWidgets.QPushButton(self.expectedSetup)
        self.AltenButton.setGeometry(QtCore.QRect(690, 20, 100, 61))
        self.AltenButton.setMinimumSize(QtCore.QSize(100, 61))
        self.AltenButton.setMaximumSize(QtCore.QSize(100, 61))
        self.AltenButton.setObjectName("AltenButton")

        self.RecieverButton = QtWidgets.QPushButton(self.expectedSetup)
        self.RecieverButton.setGeometry(QtCore.QRect(830, 20, 150, 61))
        self.RecieverButton.setMinimumSize(QtCore.QSize(150, 61))
        self.RecieverButton.setMaximumSize(QtCore.QSize(150, 61))
        self.RecieverButton.setObjectName("RecieverButton")

        self.AntenneKontrollerButton = QtWidgets.QPushButton(self.expectedSetup)
        self.AntenneKontrollerButton.setGeometry(QtCore.QRect(390, 120, 120, 61))
        self.AntenneKontrollerButton.setMinimumSize(QtCore.QSize(120, 61))
        self.AntenneKontrollerButton.setMaximumSize(QtCore.QSize(120, 61))
        self.AntenneKontrollerButton.setObjectName("AntenneKontrollerButton")

        self.UpArrow = QtWidgets.QLabel(self.expectedSetup)
        self.UpArrow.setGeometry(QtCore.QRect(440, 85, 21, 41))
        self.UpArrow.setMinimumSize(QtCore.QSize(21, 41))
        self.UpArrow.setMaximumSize(QtCore.QSize(21, 41))
        self.UpArrow.setText("")
        self.UpArrow.setObjectName("UpArrow")

        self.RightArrow1 = QtWidgets.QLabel(self.expectedSetup)
        self.RightArrow1.setGeometry(QtCore.QRect(500, 40, 51, 21))
        self.RightArrow1.setMinimumSize(QtCore.QSize(51, 21))
        self.RightArrow1.setMaximumSize(QtCore.QSize(51, 21))
        self.RightArrow1.setText("")
        self.RightArrow1.setObjectName("RightArrow1")

        self.RightArrow2 = QtWidgets.QLabel(self.expectedSetup)
        self.RightArrow2.setGeometry(QtCore.QRect(640, 40, 51, 21))
        self.RightArrow2.setMinimumSize(QtCore.QSize(51, 21))
        self.RightArrow2.setMaximumSize(QtCore.QSize(51, 21))
        self.RightArrow2.setText("")
        self.RightArrow2.setObjectName("RightArrow2")

        self.RightArrow3 = QtWidgets.QLabel(self.expectedSetup)
        self.RightArrow3.setGeometry(QtCore.QRect(780, 40, 51, 21))
        self.RightArrow3.setMinimumSize(QtCore.QSize(51, 21))
        self.RightArrow3.setMaximumSize(QtCore.QSize(51, 21))
        self.RightArrow3.setText("")
        self.RightArrow3.setObjectName("RightArrow3")

        self.FrequencyEdit = QtWidgets.QLineEdit(EditSignalRouting)
        self.FrequencyEdit.setGeometry(QtCore.QRect(310, 50, 181, 31))
        self.FrequencyEdit.setMinimumSize(QtCore.QSize(181, 31))
        self.FrequencyEdit.setMaximumSize(QtCore.QSize(181, 31))
        self.FrequencyEdit.setObjectName("FrequencyEdit")

        self.FrequencyLabel = QtWidgets.QLabel(EditSignalRouting)
        self.FrequencyLabel.setGeometry(QtCore.QRect(60, 50, 101, 31))
        self.FrequencyLabel.setMinimumSize(QtCore.QSize(101, 31))
        self.FrequencyLabel.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.FrequencyLabel.setFont(font)
        self.FrequencyLabel.setObjectName("FrequencyLabel")

        self.retranslateUi(EditSignalRouting)
        self.Monitoring.setCurrentIndex(2)
        self.CancelButton.clicked['bool'].connect(EditSignalRouting.close)
        QtCore.QMetaObject.connectSlotsByName(EditSignalRouting)

        # define the background color of the window
        pale = QtGui.QPalette()
        pale.setColor(QtGui.QPalette.Background, QtGui.QColor(248, 248, 248))
        EditSignalRouting.setPalette(pale)

    def retranslateUi(self, EditSignalRouting):
        _translate = QtCore.QCoreApplication.translate
        EditSignalRouting.setWindowTitle(_translate("EditSignalRouting", "Signalrouting bearbeiten"))
        self.ApplyButton.setText(_translate("EditSignalRouting", "Anwenden"))
        self.CancelButton.setText(_translate("EditSignalRouting", "Zurück"))
        self.HelptoolButton.setText(_translate("EditSignalRouting", "  Hilfe"))
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.headerItem().setText(0, _translate("EditSignalRouting", "Rx Antenna"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("EditSignalRouting", "None"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.BackgroundLabel1.setText(_translate("EditSignalRouting", "BackgroundLabel1"))
        self.Monitoring.setTabText(self.Monitoring.indexOf(self.tab), _translate("EditSignalRouting", "Emissionsausrüstung"))
        self.AuxiliaryOutputsLabel.setText(_translate("EditSignalRouting", "Hilfsausgänge"))
        self.SwitchPositionLabel.setText(_translate("EditSignalRouting", "Schalterpositionen (Automatisch ausgewählt basierend auf der Geräteauswahl.)"))
        self.OutPutTree.headerItem().setText(0, _translate("EditSignalRouting", "New Column"))
        self.OutPutTree.headerItem().setText(1, _translate("EditSignalRouting", "New Column"))
        item = self.PositionTable.horizontalHeaderItem(0)
        item.setText(_translate("EditSignalRouting", "Art"))
        item = self.PositionTable.horizontalHeaderItem(1)
        item.setText(_translate("EditSignalRouting", "Schalterpositionen"))
        self.Monitoring.setTabText(self.Monitoring.indexOf(self.tab_2), _translate("EditSignalRouting", "Systemkontroller"))
        self.UserMessageLabel.setText(_translate("EditSignalRouting", "Benutzermeldung"))
        self.UserMessageTest.setText(_translate("EditSignalRouting", "Benutzermeldung (Test)"))
        self.UserMessageCheckBox.setText(_translate("EditSignalRouting", "Entspricht der Meldung von \"Kalibrierung\"."))
        self.Monitoring.setTabText(self.Monitoring.indexOf(self.tab_3), _translate("EditSignalRouting", "Benutzermeldungen"))
        self.expectedSetup.setTitle(_translate("EditSignalRouting", "Erwartetes Setup"))
        self.EUTButton.setText(_translate("EditSignalRouting", "EUT"))
        self.AntenneEmpangButton.setText(_translate("EditSignalRouting", "Antenne empfangen"))
        self.KabelButton.setText(_translate("EditSignalRouting", "Kabel"))
        self.AltenButton.setText(_translate("EditSignalRouting", "Antennekontroller"))
        self.RecieverButton.setText(_translate("EditSignalRouting", "PushButton"))
        self.AntenneKontrollerButton.setText(_translate("EditSignalRouting", "Antennekontroller"))
        self.FrequencyEdit.setToolTip(_translate("EditSignalRouting", "Definieren Sie die Startfrequenz."))
        self.FrequencyEdit.setText(_translate("EditSignalRouting", "800MHz"))
        self.FrequencyLabel.setText(_translate("EditSignalRouting", "Frequenz:"))
        uparrow = cv.imread("./icon_materials/17.png", -1)
        uparrow = png_preprocess(uparrow, 31)
        self.UpArrow.setPixmap(QtGui.QPixmap(uparrow))


# This class defines the "Versuchsaufbau" window
# The functions are not completed and activated.
# It's Qt-Designer file is "versuchsaufbau.ui" in folder "uifiles"
class Ui_TestSetUp(object):
    def setupUi(self, TestSetUp):
        TestSetUp.setObjectName("TestSetUp")
        TestSetUp.setWindowModality(QtCore.Qt.WindowModal)
        TestSetUp.resize(1401, 792)
        TestSetUp.setMinimumSize(QtCore.QSize(1401, 792))
        TestSetUp.setMaximumSize(QtCore.QSize(1401, 792))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        TestSetUp.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon_materials/4.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        TestSetUp.setWindowIcon(icon)

        self.Warning = QtWidgets.QLabel(TestSetUp)
        self.Warning.setGeometry(QtCore.QRect(50, 720, 51, 51))
        self.Warning.setMinimumSize(QtCore.QSize(51, 51))
        self.Warning.setMaximumSize(QtCore.QSize(51, 51))
        self.Warning.setText("")
        self.Warning.setObjectName("Warning")

        self.TestSetUpGroup = QtWidgets.QGroupBox(TestSetUp)
        self.TestSetUpGroup.setGeometry(QtCore.QRect(20, 70, 1361, 631))
        self.TestSetUpGroup.setMinimumSize(QtCore.QSize(1361, 631))
        self.TestSetUpGroup.setMaximumSize(QtCore.QSize(1361, 631))
        self.TestSetUpGroup.setTitle("")
        self.TestSetUpGroup.setObjectName("TestSetUpGroup")

        self.SignalTabel = QtWidgets.QTableWidget(self.TestSetUpGroup)
        self.SignalTabel.setGeometry(QtCore.QRect(25, 160, 1311, 451))
        self.SignalTabel.setMinimumSize(QtCore.QSize(1311, 451))
        self.SignalTabel.setMaximumSize(QtCore.QSize(1311, 451))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.SignalTabel.setFont(font)
        self.SignalTabel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.SignalTabel.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SignalTabel.setObjectName("SignalTabel")
        self.SignalTabel.setColumnCount(5)
        self.SignalTabel.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SignalTabel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SignalTabel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SignalTabel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SignalTabel.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SignalTabel.setHorizontalHeaderItem(4, item)

        self.NewButton = QtWidgets.QPushButton(self.TestSetUpGroup)
        self.NewButton.setGeometry(QtCore.QRect(470, 100, 131, 41))
        self.NewButton.setMinimumSize(QtCore.QSize(131, 41))
        self.NewButton.setMaximumSize(QtCore.QSize(131, 41))
        self.NewButton.setObjectName("NewButton")

        self.CopyButton = QtWidgets.QPushButton(self.TestSetUpGroup)
        self.CopyButton.setEnabled(False)
        self.CopyButton.setGeometry(QtCore.QRect(610, 100, 131, 41))
        self.CopyButton.setMinimumSize(QtCore.QSize(131, 41))
        self.CopyButton.setMaximumSize(QtCore.QSize(131, 41))
        self.CopyButton.setObjectName("CopyButton")

        self.EditButton = QtWidgets.QPushButton(self.TestSetUpGroup)
        self.EditButton.setEnabled(False)
        self.EditButton.setGeometry(QtCore.QRect(750, 100, 131, 41))
        self.EditButton.setMinimumSize(QtCore.QSize(131, 41))
        self.EditButton.setMaximumSize(QtCore.QSize(131, 41))
        self.EditButton.setObjectName("EditButton")

        self.DeleteButton = QtWidgets.QPushButton(self.TestSetUpGroup)
        self.DeleteButton.setEnabled(False)
        self.DeleteButton.setGeometry(QtCore.QRect(890, 100, 131, 41))
        self.DeleteButton.setMinimumSize(QtCore.QSize(131, 41))
        self.DeleteButton.setMaximumSize(QtCore.QSize(131, 41))
        self.DeleteButton.setObjectName("DeleteButton")

        self.ImportButton = QtWidgets.QPushButton(self.TestSetUpGroup)
        self.ImportButton.setGeometry(QtCore.QRect(1030, 100, 131, 41))
        self.ImportButton.setMinimumSize(QtCore.QSize(131, 41))
        self.ImportButton.setMaximumSize(QtCore.QSize(131, 41))
        self.ImportButton.setObjectName("ImportButton")

        self.systemTestButton = QtWidgets.QPushButton(self.TestSetUpGroup)
        self.systemTestButton.setEnabled(False)
        self.systemTestButton.setGeometry(QtCore.QRect(1180, 100, 151, 41))
        self.systemTestButton.setMinimumSize(QtCore.QSize(151, 41))
        self.systemTestButton.setMaximumSize(QtCore.QSize(151, 41))
        self.systemTestButton.setCheckable(False)
        self.systemTestButton.setChecked(False)
        self.systemTestButton.setObjectName("systemTestButton")

        self.ExpandButton = QtWidgets.QToolButton(self.TestSetUpGroup)
        self.ExpandButton.setGeometry(QtCore.QRect(30, 100, 171, 41))
        self.ExpandButton.setMinimumSize(QtCore.QSize(171, 41))
        self.ExpandButton.setMaximumSize(QtCore.QSize(171, 41))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.ExpandButton.setFont(font)
        self.ExpandButton.setAutoRaise(True)
        self.ExpandButton.setStyleSheet("color:rgb({},{},{},255)".format(92, 174, 219))
        self.ExpandButton.setObjectName("ExpandButton")

        self.CollposeButton = QtWidgets.QToolButton(self.TestSetUpGroup)
        self.CollposeButton.setGeometry(QtCore.QRect(210, 100, 241, 41))
        self.CollposeButton.setMinimumSize(QtCore.QSize(241, 41))
        self.CollposeButton.setMaximumSize(QtCore.QSize(241, 41))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.CollposeButton.setFont(font)
        self.CollposeButton.setAutoRaise(True)
        self.CollposeButton.setStyleSheet("color:rgb({},{},{},255)".format(92, 174, 219))
        self.CollposeButton.setObjectName("CollposeButton")

        self.SystemControllerLabel = QtWidgets.QLabel(self.TestSetUpGroup)
        self.SystemControllerLabel.setGeometry(QtCore.QRect(30, 50, 250, 31))
        self.SystemControllerLabel.setMinimumSize(QtCore.QSize(250, 31))
        self.SystemControllerLabel.setMaximumSize(QtCore.QSize(250, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SystemControllerLabel.setFont(font)
        self.SystemControllerLabel.setObjectName("SystemControllerLabel")

        self.KontrollerComBoBox = MyComboBox(self.TestSetUpGroup)
        self.KontrollerComBoBox.setGeometry(QtCore.QRect(320, 50, 1011, 31))
        self.KontrollerComBoBox.setMinimumSize(QtCore.QSize(1011, 31))
        self.KontrollerComBoBox.setMaximumSize(QtCore.QSize(1011, 31))
        self.KontrollerComBoBox.setEditable(True)
        self.KontrollerComBoBox.setObjectName("KontrollerComBoBox")

        self.label = QtWidgets.QLabel(self.TestSetUpGroup)
        self.label.setGeometry(QtCore.QRect(600, 0, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.WarningLabel = QtWidgets.QLabel(TestSetUp)
        self.WarningLabel.setGeometry(QtCore.QRect(130, 730, 251, 31))
        self.WarningLabel.setMinimumSize(QtCore.QSize(251, 31))
        self.WarningLabel.setMaximumSize(QtCore.QSize(251, 31))
        self.WarningLabel.setObjectName("WarningLabel")

        self.ApplyButton = QtWidgets.QPushButton(TestSetUp)
        self.ApplyButton.setGeometry(QtCore.QRect(1070, 720, 131, 41))
        self.ApplyButton.setMinimumSize(QtCore.QSize(131, 41))
        self.ApplyButton.setMaximumSize(QtCore.QSize(131, 41))
        self.ApplyButton.setDefault(True)
        self.ApplyButton.setObjectName("ApplyButton")

        self.CancelButton = QtWidgets.QPushButton(TestSetUp)
        self.CancelButton.setGeometry(QtCore.QRect(1220, 720, 131, 41))
        self.CancelButton.setMinimumSize(QtCore.QSize(131, 41))
        self.CancelButton.setMaximumSize(QtCore.QSize(131, 41))
        self.CancelButton.setObjectName("CancelButton")

        self.retranslateUi(TestSetUp)
        self.CancelButton.clicked['bool'].connect(TestSetUp.close)
        QtCore.QMetaObject.connectSlotsByName(TestSetUp)
        self.KontrollerComBoBox.clicked.connect(self.systemcontrollerselection)
        self.NewButton.clicked.connect(self.signalroutingcreating)

        # define the background color of the window
        pale = QtGui.QPalette()
        pale.setColor(QtGui.QPalette.Background, QtGui.QColor(248, 248, 248))
        TestSetUp.setPalette(pale)


    def retranslateUi(self, TestSetUp):
        _translate = QtCore.QCoreApplication.translate
        TestSetUp.setWindowTitle(_translate("TestSetUp", "Versuchsaufbau"))
        item = self.SignalTabel.horizontalHeaderItem(0)
        item.setText(_translate("TestSetUp", "Frequenz"))
        item = self.SignalTabel.horizontalHeaderItem(1)
        item.setText(_translate("TestSetUp", "Gerätenamen"))
        item = self.SignalTabel.horizontalHeaderItem(2)
        item.setText(_translate("TestSetUp", "Schalter"))
        item = self.SignalTabel.horizontalHeaderItem(3)
        item.setText(_translate("TestSetUp", "Hilfs"))
        item = self.SignalTabel.horizontalHeaderItem(4)
        item.setText(_translate("TestSetUp", "Benutzermeldung"))
        self.NewButton.setText(_translate("TestSetUp", "Neu"))
        self.CopyButton.setText(_translate("TestSetUp", "Kopieren"))
        self.EditButton.setText(_translate("TestSetUp", "Bearbeiten"))
        self.DeleteButton.setText(_translate("TestSetUp", "Löschen"))
        self.ImportButton.setText(_translate("TestSetUp", "Importieren"))
        self.systemTestButton.setText(_translate("TestSetUp", "System Testen"))
        self.ExpandButton.setText(_translate("TestSetUp", "+ Aller erweitern"))
        self.CollposeButton.setText(_translate("TestSetUp", "- Alle zusammenbrechen"))
        self.SystemControllerLabel.setText(_translate("TestSetUp", "Aktive Systemkontroller:"))
        self.KontrollerComBoBox.setToolTip(_translate("TestSetUp", "Wählen Sie alle Systemkontroller aus, die diesem Testaufbau zugeordnet sind."))
        self.KontrollerComBoBox.setCurrentText(_translate("TestSetUp", "None"))
        self.label.setText(_translate("TestSetUp", "Signal Routing"))
        self.WarningLabel.setText(_translate("TestSetUp", "Das Signal Routing ist leer!"))
        self.ApplyButton.setText(_translate("TestSetUp", "Anwenden"))
        self.CancelButton.setText(_translate("TestSetUp", "Zurück"))
        warningsign = cv.imread("./icon_materials/16.png", -1)
        warningsign = png_preprocess(warningsign, 51)
        self.Warning.setPixmap(QtGui.QPixmap(warningsign))

    # enable the choice of the system controller
    def systemcontrollerselection(self):
        if self.KontrollerComBoBox.currentText() == "None":
            widget = QtWidgets.QDialog()
            ui = Ui_SystemControllerSelection()
            ui.setupUi(widget)
            widget.exec_()

    # open the "EditSignalRouting" window to create or choose a signal routing
    def signalroutingcreating(self):
        widget = QtWidgets.QDialog()
        ui = Ui_EditSignalRouting()
        ui.setupUi(widget)
        widget.exec_()

# function that can process .jpg image
def pic_preprocess(img, new_height):
    show = cv.cvtColor(img, cv.COLOR_BGR2RGB)
    width = show.shape[1]
    height = show.shape[0]
    ratio = float(height / width)
    new_width = int(new_height / ratio)
    show = cv.resize(show, (new_width, new_height))
    totalBytes = show.nbytes
    bytesPerLine = int(totalBytes / new_height)
    return QtGui.QImage(show, new_width, new_height, bytesPerLine, QtGui.QImage.Format_RGB888)

# function that can process .png image
def png_preprocess(img, new_height):
    width = img.shape[1]
    height = img.shape[0]
    ratio = float(height / width)
    new_width = int(new_height / ratio)
    show = cv.resize(img, (new_width, new_height))
    totalBytes = show.nbytes
    bytesPerLine = int(totalBytes / new_height)
    return QtGui.QImage(show, new_width, new_height, bytesPerLine, QtGui.QImage.Format_ARGB32)


# the Class MyComboBox creats a costumized Combo Box. It can be triggered by mouse click.
class MyComboBox(QtWidgets.QComboBox):
    clicked = QtCore.pyqtSignal()          # create a signal
    def showPopup(self):            # rewrite the "showPopup" function
        self.clicked.emit()         # the created signal can be emitted
        super(MyComboBox, self).showPopup()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TestSetUp = QtWidgets.QWidget()
    ui = Ui_TestSetUp()
    ui.setupUi(TestSetUp)
    TestSetUp.show()
    sys.exit(app.exec_())